
[build]
command = "npm install && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"  # ensures compatibility with Vite/Rollup native modules

[dev]
command = "npm run dev"
port = 5173