# netlify.toml
[build]
# Build command: clean install then build
command = "npm ci && npm run build"
# Directory where Vite outputs the built files
publish = "dist"

[build.environment]
# Use a stable Node version
NODE_VERSION = "18"